# Formato personalizado
format = '''
$username$hostname \[$directory$package\] $cmd_duration $fill$time$os
$character '''

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = true

# Paleta de color personalizada
palette = 'patata'



# Modulos personalizados

[username]
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = ' on [$ssh_symbol](bold blue)[$hostname](bold red)'
disabled = false

[directory]
format = '[$path]($style)[$read_only]($read_only_style)'
truncation_length = 8

[package]
format = 'via [ğŸ $version](208 bold) '

[cmd_duration]
min_time = 200
format = 'took [$duration](bold green)'

[fill]
symbol = ' '

[time]
style = "purple"
disabled = false
format = '[\[$time\]]($style) '
time_format = '%R'
utc_time_offset = '2'
time_range = '00:00-23:59'

[os]
format = '[\[($symbol$name)\]]($style)'
style = "bold blue"
disabled = false

[os.symbols]
Windows = "î˜ª "
Arch = "Arch es el mejor! "

#[battery]
#format = '[$symbol$percentage]($style)'
#disable = false
#full_symbol = 'ğŸ”‹ '
#charging_symbol = 'âš¡ï¸ '
#discharging_symbol = 'ğŸ’€ '

#[battery.display]
#threshold = 100
#style = 'bold red'

[character] 
success_symbol = '[âœ](bold green)'
error_symbol = '[âœ](bold red)'

# Paletas personalizadas
[palettes.patata]
# Sobreescribir color existente
#blue = '22'

# Definir un nuevo color
#mustard = '#af8700'
